# cargo-features = ["build-std"]

[workspace]
resolver = "3"
members = [
    "init/start",
    "init/start-impl",
    "mm/core",
    "arch",
    "drivers/core",
    "kernel/core",
    "kernel/macros",
    ]
default-members = ["init/start"]

[workspace.package]
publish = false
version = "0.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
uefi = {version = "0.37.0", default-features = false}
cfg-if = {version = "1"}
bytemuck = {version = "1", default-features = false, features = ["derive"]}
spin = {version = "0.10", default-features = false}
cc = {version = "1", features = ["parallel"]} # for build scripts
ringbuf = {version = "0.4.8", default-features = false}
multiboot2 = {version = "0.24.1",default-features = false}
log = {version = "0.4", default-features = false}
[workspace.lints.clippy]
arithmetic_side_effects = "deny"
# Default usually implies no major allocations take place, which can simply not be true
new_without_default = "allow"

[workspace.lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    # bochs option is only available on x86, when using the bochs emulator
    # Defaults to a pseudo breakpoint
    'cfg(breakpoint_type, values("bochs"))',
    'cfg(docrs)',
    # Document certain functions which shouldn't be used by most
    # developers. Such as functions that shouldn't be called inside of rust
    'cfg(document_niche)',
    ]
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
