[package]
name = "oes-kernel-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Be carful adding ANY workspace dependencies
oes-arch = {path = "../../arch"}
oes-drivers-core = {path = "../../drivers/core"}
spin = {workspace = true, features = ["mutex","ticket_mutex","use_ticket_mutex"]}
ringbuf = {workspace = true}
cfg-if = {workspace = true}
# Not a workspace dependency since we only need back traces defined in one place, ie panic handler
# The only crate we want to keep defaults as it won't pull in
unwinding = {version = "0.2",default-features = false, features = ["personality","unwinder","fde-static"]}
oes-macros = {path = "../macros"}
log = {workspace = true}
[lints]
workspace = true

[features]
alloc = []
