# Tests are under kernel-cores
[package]
name = "oes-macros"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
proc-macro2 = {version = "1.0"}
quote = {version = "1.0"}
syn = {version = "2.0", features = ["full","extra-traits"]}

[lints]
workspace = true

[lib]
proc-macro = true
