[package]
name = "oes-arch-common"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
uefi = {workspace = true, optional = true}
bytemuck = {workspace = true}
[features]
uefi = ["dep:uefi"]
multiboot = []
[build-dependencies]
bindgen = "0.72.1"
