[package]
name = "oes-init-start-impl"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
oes-arch = {path = "../../arch"}
# Not a workspace dependency since we only need back traces defined in one place, ie panic handler
# The only crate we want to keep defaults as it won't pull in
unwinding = {version = "0.2",default-features = true, features = ["personality"]}
[lints]
workspace = true

[features]
uefi = ["oes-arch/uefi"]